version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn -B package --file pom.xml
      - mv target/stefansreleasedemomaven-0.0.1-SNAPSHOT.jar target/stefansreleasedemomaven.jar
artifacts:
  files:
    - target/*.jar